"""
Django settings for students project.

Generated by 'django-admin startproject' using Django 2.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))



from linebot import (
    LineBotApi, WebhookHandler
)
from linebot.exceptions import (
    InvalidSignatureError
)
from linebot.models import *





# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'Ub8e3cf75739079f25a50f82b2cbd4c63'
# 必須放上自己的Channel Access Token
LINE_CHANNEL_ACCESS_TOKEN ='{
  "p": "7xOtwzxZcSMg0cDDXlIytC87JQjpCkTH81iYdJKoFz6hvIAKBdo_yVl4PLMym-G-alJtcjFx9Yvzh7dzh-07Ds5cn4oCWAYoL5bsvOoVye12PUbrmognx-Xi5T_ffjtxMvLTvatdSt-egandV8No9enFn7OZqZSzpMe78TAlTwk",
  "kty": "RSA",
  "q": "wee4dUBlVjJvVzejU8DK8pXHqPzZ0Kz7iRt1l7V6evWERev8CXoHdxuTU7NgnXKmG_YB5qxA_B0zuVoSo56cA59JzaU_tVhTeZ7i4RFlt-xG3QA1gpSKcQPvpWgNOVk1HhKQYntzlYzHoOmcl80r1wywfUTXHrbyggO3x9c1SKc",
  "d": "jCJ1fpFoDJCgL0ZIOqjEsl6R-RCfQRiAJ4QZL9IR7UXgwEseSjRMzilzHJmhkIXHvidsuO5fvoe-e4U6KRU0BNLbGxuFMTXccpG3aXjXl1Nt8WjUz8P7Dx7UkZVJkjS-KzBV3ZHgu7SByyToHBOuuiBCtpUfhQpyVEh9wwxKli_fDagPVJJbhPYTWLR_8u20qbBkcXvXGh8y9XU6scSaLtzRlos9fOif0ac3vmeBO1Cxe-7jxeT2mPby5o17LyyBIyzBMlqDpt_Y64hdonTYfxkFK9Ugf_J_gweAZw6J9EZQsuVP4JWnI7XEcJFm0rrqFFBVaAlRduLTi0LnQUAJQQ",
  "e": "AQAB",
  "use": "sig",
  "kid": "74d89b23-2d34-4faa-afca-f1f3a43ff909",
  "qi": "VYIMAC_dQNBTh9tADv-jfMPO0pu6WxdL6z8Sq9hTjx8z9K-TnsqfaxDTjB70OhZL5zdAMtU2tdhs1GY1iRr9QL7lzqpNfUlxzoz-QukD1fkRf1OOojdY8iUCfHWOyyp_R6TTeNZlyICSFdt1nu3BVfDf6G5SYuJe_fI9LWxd-u8",
  "dp": "zg4y9JO-LyHstnwiptfHtb8Dhe8BFAWmJFnWxJpmX-pucc4VVWf_FCaV2BNG6k2N1YuHoyV0qALgebemzp-sCB3afPLxBDcCScoV7tj-wJR3FWdbx0vUpZjAj4AWu3C2JwhdcRsShGbp8a2bBXp5q4G5_-RG638rujkgBkfN0Ck",
  "alg": "RS256",
  "dq": "sfv8uMOPQPuyb6BGbw48O0d4qYjOdlkR2dw2qDaQYmUSMQxXoGs-hvns1ZuFR4CBMJEzVYUvcTtsyun-yelA06JWoEjanZ6hoLVTE7xgXd6nfRxAAchO-0XdpzpHSSi1NRFdLsiaY9-BLhbBAiX148NmDNYvj6XmG6lF_E1yP2k",
  "n": "tRY9BaCxL0-D8mI0s_IvqpGZGwIfJJrUcslOdhe2gH5iha7drqTVTwnW4a1UTsgNbTVMV-051Mn5bytg4y82OQNpclV9WT0ldMt-WbBpuGDH_qlFcHzA4PnmmhsnBsFj1-8LhLaY_oMbW1trpHlHzs9YIJZU5LESGtPkre86ycQiuZKVwIjUQMEf26s03iO1i9XzkRmJoB-VB2ilKXYpOos_rYbrDAaf3txTEaswTGL5UEAuBmMm9EVrLIqZxYDwdzW-PxYRAqwy43qo63vOB8gRUUGu6m-hTs_p-EJAL6LZPBkrwDGHaKXmCRPEVjfdvMnK9QBthLW7IJv50m4W3w"
}'
# 必須放上自己的Channel Secret
LINE_CHANNEL_SECRET='8aa414aee6a24cfa9763474df4b5cb3e'

# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = ['*']
DEBUG = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'studentsapp',
    #'test2api', # 新增的 app
    'func1api',
    'hotelapi',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'students.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'students.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_L10N = True

USE_TZ = True

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
#SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [  #加入 static 路徑
	os.path.join(BASE_DIR, 'static'),
]
