"""
Django settings for students project.

Generated by 'django-admin startproject' using Django 2.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))



from linebot import (
    LineBotApi, WebhookHandler
)
from linebot.exceptions import (
    InvalidSignatureError
)
from linebot.models import *





# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'Ub8e3cf75739079f25a50f82b2cbd4c63'
# 必須放上自己的Channel Access Token
LINE_CHANNEL_ACCESS_TOKEN ='{"p": "_7rpRpsoDCxFT3QDyRhjpKtPKROJRIxLkGMkaJankpa5wRYJu4BRiBlwb2Ah9iDOXNKaV_Vnb36DXwtMuHfCPDCtCPqGk_GtC-PMQzI_9_xP2RsFp8zYZeMBBlKRVy0Yvkg1e4ixSKEC-4TCfX6TkzSNkgLHpWz7BIO1wistGoU",
  "kty": "RSA",
  "q": "m-7WcJUGWstjekFYl8PHMRL1gW9tprvFPNlxiCpY9cZy-D1CvtXztk4g_XLLU4iydAQhuOWhTLLpUp-FX__l_8GliSR5rDFDR0n6VzP8g4WgOvUS55YHMIEge6ktxR6pGAUtd6UG7HQf3ZRFoIH0F3xoUPQdXC2HOWWoXo2x43k",
  "d": "ZIz48gqLcLJ4VFfQFgZ4aCzprRB7bQUa1UHAYGbDa38Bz6KuQtW3kCa1lO-TDB0IK9rdFQSjsTkJ4wTSNEriqlGYuhoMAsnsrjpFr3eO4bZAp-R5lUs70BPnJJOp6JQ5Odww4wl_fzQMa3RU3Bz_LSgtSlLEfW66u31xs9hVUlZG3jilceVFriAQ0ABotB1Ub2oeL_AKXQTNy0j5GBReJM-mFhD-W3D63czZtIff4XAUH6_mMFCRxvrmFCR9Vdnv9XHQ_6zHlGGUVjc0LJ1Gnx-_LquQF8lPV5VKSdxcmlKmA6XZQD3QfUjDAufvw9qKf_XyL6WyOdrE3TVV83ZR4Q",
  "e": "AQAB",
  "use": "sig",
  "kid": "9e54f08c-2807-4a11-be54-3e19afe398bf",
  "qi": "VCjoB432S71DWc_atLtIb7ZvJo3hbEPbYcWDqX1suC_awGkUNogS5ahWIazC-2o9s3o8kMVx0_-8XO0KwThwrMRKeFiVXlNwL545Nba3oH3wt_hph8vGBDOjiBJKdXIZl_iywFGGdkpJkd9z0e9Fb5Gz5g7G3bf70o8k6be-SQw",
  "dp": "mRQLm6Y43MCLZLovoeqliua45f-5xXytpuqR2sGD4a2z168XeFOhenSv5xuGeMy-erXeihRuLEFw5i3faPTXIiyJB7zfXiPm0B02Imsr-4ffTDhutDlct_CgpmY6dhKaoxyaVy5F4RHwtRqNSY3BTPbCX8qmM5H-2H73CBnMT_k",
  "alg": "RS256",
  "dq": "Vqs3UTfjYk-tqOPtI91TN3l8L0cJwSSYiiupqK8w5to4SLV0BbHRVcCzIWvOi01tMoKhY61uK709Zgj4DtWitrahFUrKveRbqqH5nMJuVYPN_Tb-HO4MbO84aMMth2R1Q76M-PUmlgItO_EPihjw3KTvLh-guf0sLcDNBlDnULE",
  "n": "m8TBOVU6tgvtYQiKfSsYCJnPluoH3RluxWiqwZ_Fb-i_Kg2s4GHBSJlZrAbyYGv7I99N8i1aSl_0vrRrshDgdj5udWAmUmTfMmUXpyZ7d1gs9kUzDamnnFJEyCtqOEcgL_WC9qcwOh0nIXZPjZG0bq-1RQDVfamZwjekj4ZaElCoSHWUQ29MvlcFv_Im88qx_ydPDwd3EqPHzA3vEOA7cnGZYP5JHk9mUtjCxEe9KkGelNYPuzogWGYlmSRqCnmuL2pAjwVtCb39EVHgQqzvYVLUz6wdCXrlC5LzWWgF6pS6DPOWW7vnL1JUCjfDWjfQ5vPtRfv4XEoQ48uv_cp33Q"
}'
# 必須放上自己的Channel Secret
LINE_CHANNEL_SECRET='3337ac546482a32342cba7d0a5f5824f'

# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = ['*']
DEBUG = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'studentsapp',
    #'test2api', # 新增的 app
    'func1api',
    'hotelapi',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'students.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'students.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_L10N = True

USE_TZ = True

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
#SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [  #加入 static 路徑
	os.path.join(BASE_DIR, 'static'),
]
